package com.example.ws;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 2.0.0.4
//
// Created by Quasar Development at 18-29-2014
//
//---------------------------------------------------



import org.ksoap2.SoapEnvelope;
import org.ksoap2.serialization.*;
import org.kxml2.io.KXmlParser;
import org.kxml2.kdom.Element;
import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlPullParserFactory;
import org.xmlpull.v1.XmlSerializer;

import java.io.IOException;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Vector;
import java.io.StringReader;
import java.io.StringWriter;


public class ExtendedSoapSerializationEnvelope extends SoapSerializationEnvelope {

    public interface IReferenceObject
    {
    }

    static HashMap< String,Class> classNames = new HashMap< String, Class>();

    HashMap< Object,String> reverseReferencesTable = new HashMap< Object, String>();
    HashMap< String,Object> referencesTable = new HashMap< String,Object>();
    private final String MsNs="http://schemas.microsoft.com/2003/10/Serialization/";
    protected static final int QNAME_NAMESPACE = 0;
    private static final String TYPE_LABEL = "type";

    public ExtendedSoapSerializationEnvelope() {
        super(SoapEnvelope.VER11);
        implicitTypes = true;
        dotNet = true;

        new MarshalGuid().register(this);
        new MarshalDateTime().register(this);
        new MarshalFloat().register(this);
    }

    @Override
    public void writeObjectBody(XmlSerializer writer, KvmSerializable obj) throws IOException {
        if(obj instanceof AttributeContainer)
        {
            AttributeContainer soapObject= (AttributeContainer) obj;
            int cnt = soapObject.getAttributeCount();
            for (int counter = 0; counter < cnt; counter++) {
                AttributeInfo attributeInfo = new AttributeInfo();
                soapObject.getAttributeInfo(counter, attributeInfo);
                writer.attribute(attributeInfo.getNamespace(), attributeInfo.getName(), attributeInfo.getValue()!=null? attributeInfo.getValue().toString():"");
            }
        }
        super.writeObjectBody(writer,obj);
    }

    @Override
    protected void writeProperty(XmlSerializer writer, Object obj, PropertyInfo type) throws IOException {
        if (obj == null) {
            writer.attribute(xsi, "nil", "true");
            return;
        }

        if(reverseReferencesTable.containsKey(obj))
        {
            //this object has been already serialized so use Ref instead
            String id=reverseReferencesTable.get(obj);
            writer.attribute(MsNs, "Ref",id);
            return;
        }
        else
        {

            if(obj instanceof IReferenceObject)
            {
                String id=String.format("i%d", reverseReferencesTable.size() + 1);
                reverseReferencesTable.put(obj,id);
                writer.attribute(MsNs, "Id",id);
            }

            Object[] qName = getInfo(null, obj);
            if (!type.multiRef && qName[2] == null)
            {
                if (!implicitTypes || (obj.getClass() != type.type && !(obj instanceof Vector ) && type.type!=String.class)) {
                    String xmlName=Helper.getKeyByValue(classNames,obj.getClass());
                    if(xmlName!=null)
                    {
                        String[] parts=xmlName.split("\\^\\^");
                        String prefix = writer.getPrefix(parts[0], true);
                        writer.attribute(xsi, TYPE_LABEL, prefix + ":" +parts[1]);
                    }
                    else
                    {
                        String prefix = writer.getPrefix(type.namespace, true);
                        writer.attribute(xsi, TYPE_LABEL, prefix + ":" + obj.getClass().getSimpleName());
                    }
                }
                //super.writeProperty(writer,obj,type);

                try {
                    Method method = this.getClass().getSuperclass().getDeclaredMethod("writeElement",org.xmlpull.v1.XmlSerializer.class,Object.class,PropertyInfo.class,Object.class);
                    method.setAccessible(true);
                    method.invoke(this,writer, obj, type, qName[QNAME_MARSHAL]);
                } catch (NoSuchMethodException e) {
                    e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
                } catch (IllegalAccessException e) {
                    e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
                } catch (InvocationTargetException e) {
                    e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
                }
                //writeElement(writer, obj, type, qName[QNAME_MARSHAL]);
            }
            else {
                super.writeProperty(writer, obj, type);
            }
        }
    }

    public SoapObject GetExceptionDetail(Element detailElement) {
         Element errorElement=detailElement.getElement(0);
         return GetSoapObject(errorElement);
    }

    public SoapObject GetSoapObject(Element detailElement) {
        try{
            XmlSerializer xmlSerializer = XmlPullParserFactory.newInstance().newSerializer();
            StringWriter writer = new StringWriter();
            xmlSerializer.setOutput(writer);
            detailElement.write(xmlSerializer);
            xmlSerializer.flush();
        
            XmlPullParser xpp = new KXmlParser();
            xpp.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, true);
        
            xpp.setInput(new StringReader(writer.toString()));
            xpp.nextTag();
            SoapObject soapObj = new SoapObject(detailElement.getNamespace(),detailElement.getName());
            readSerializable(xpp,soapObj);
            return soapObj;
        }
        catch (java.lang.Exception ex)
        {
            ex.printStackTrace();
        }
        return null;
    }

    public Object GetHeader(Element detailElement) {
        if(detailElement.getText(0)!=null)
        {
            SoapPrimitive primitive = new SoapPrimitive(detailElement.getNamespace(),detailElement.getName(),detailElement.getText(0));
            return  primitive;
        }
    
        return GetSoapObject(detailElement);
    }
    
    public void Add(String id,Object obj)
    {
        if(!referencesTable.containsKey(id))
        {
            referencesTable.put(id,obj);
        }
    }

    public Object get(AttributeContainer soap,Class cl)
    {
        if(soap==null)
        {
            return null;
        }
        try
        {
            Object refAttr=Helper.getAttribute(soap,"Ref","http://schemas.microsoft.com/2003/10/Serialization/");
            if(refAttr!=null )
            {
                String ref=(String)refAttr;
                return referencesTable.get(ref);
            }
            else
            {

                if(soap instanceof SoapObject)
                {
                    String key=String.format("%s^^%s",((SoapObject)soap).getNamespace(),((SoapObject)soap).getName());
                    if(classNames.containsKey(key))
                    {
                        cl=classNames.get(key);
                    }
                }
                Constructor ctor = cl.getConstructor(AttributeContainer.class,ExtendedSoapSerializationEnvelope.class);
                return ctor.newInstance(soap,this);
            }
        }
        catch (java.lang.Exception ex)
        {
            ex.printStackTrace();
            return null;
        }
    }
} 

