package com.example.ws;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 2.0.0.4
//
// Created by Quasar Development at 18-29-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class getIp_Lokal_dtResponse_getIp_Lokal_dtResult extends AttributeContainer implements KvmSerializable,java.io.Serializable
{

    public getIp_Lokal_dtResponse_getIp_Lokal_dtResult ()
    {
    }

    public getIp_Lokal_dtResponse_getIp_Lokal_dtResult (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;


        SoapObject soapObject=(SoapObject)inObj;  


    }

    @Override
    public Object getProperty(int propertyIndex) {
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 0;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

}
