package com.example.ws;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 2.0.0.4
//
// Created by Quasar Development at 18-29-2014
//
//---------------------------------------------------



public interface IServiceEvents
{
    public void Starting();
    public void Completed(OperationResult result);
}
