package com.example.ws;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 2.0.0.4
//
// Created by Quasar Development at 18-29-2014
//
//---------------------------------------------------

import generated.newdataset.Table1;

import java.util.Hashtable;
import java.util.Vector;

import org.ksoap2.serialization.*;



												//  extends Vector< [ name of model object ]>
public class SELECT_DBResponse_SELECT_DBResult extends Vector< Table1>  //extends AtributeContainer<tTopGoalScorer>
		implements KvmSerializable, java.io.Serializable {

	
	private static final long serialVersionUID = -6519360083369798703L;

	public SELECT_DBResponse_SELECT_DBResult() {
	}

	public SELECT_DBResponse_SELECT_DBResult(AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope) {

		if (inObj == null)
			return;

		SoapObject soapObject = (SoapObject) inObj;
		
		//*********  if it is valid WSDL object then implement this code:
//		SoapObject soapObject=(SoapObject)inObj;
        int size = soapObject.getPropertyCount();
        for (int i0=0;i0< size;i0++)
        {
            Object obj = soapObject.getProperty(i0);
            if (obj!=null && obj instanceof AttributeContainer)
           {
                AttributeContainer j =(AttributeContainer) soapObject.getProperty(i0);
		
					// replace tTopGoalScorer name with model name of class [object]:
                Table1 j1= (Table1)envelope.get(j,Table1.class);  
		
                add(j1);
            }
        }
	}

	@Override
	public Object getProperty(int propertyIndex) {
		//*********  if it is valid WSDL object then implement this code:
		return this.get(propertyIndex);
//		return null;
	}

	@Override
	public int getPropertyCount() {
		//*********  if it is valid WSDL object then implement this code:
		return this.size();
//		return 0;
	}

	@Override
	public void getPropertyInfo(int propertyIndex,
			@SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
		//*********  if it is valid WSDL object then implement this code:
//		info.name = [ name of the model object ] 
//        info.type = [ name of the model class object ] 
//    	info.namespace= [ valid namespace of web service URL ] 
	}

	@Override
	public void setProperty(int arg0, Object arg1) {
	}

}
