package com.example.ws;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 2.0.0.4
//
// Created by Quasar Development at 18-29-2014
//
//---------------------------------------------------

import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class zemi_dsResponse_zemi_dsResult extends AttributeContainer implements
		KvmSerializable, java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 560102988929955414L;

	public zemi_dsResponse_zemi_dsResult() {
	}

	public zemi_dsResponse_zemi_dsResult(AttributeContainer inObj,
			ExtendedSoapSerializationEnvelope envelope) {

		if (inObj == null)
			return;

		SoapObject soapObject = (SoapObject) inObj;

	}

	@Override
	public Object getProperty(int propertyIndex) {
		return null;
	}

	@Override
	public int getPropertyCount() {
		return 0;
	}

	@Override
	public void getPropertyInfo(int propertyIndex,
			@SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
	}

	@Override
	public void setProperty(int arg0, Object arg1) {
	}

}
